// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDML2mI_9tuAHWTRQpkxO_jnZK-57OCpF4',
    appId: '1:806159169040:web:cf2454676e4a247616fc95',
    messagingSenderId: '806159169040',
    projectId: 'privora-9195c',
    authDomain: 'privora-9195c.firebaseapp.com',
    storageBucket: 'privora-9195c.firebasestorage.app',
    measurementId: 'G-94C8L8GSB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrEUpHzA4NkQfP2l3IZ0o8DjPSuactEio',
    appId: '1:806159169040:android:c96a425a090f2e7b16fc95',
    messagingSenderId: '806159169040',
    projectId: 'privora-9195c',
    storageBucket: 'privora-9195c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV8_VOXD47eRrdPlzzYz-nGaueJcH6lSs',
    appId: '1:806159169040:ios:b680c797a8ccab2f16fc95',
    messagingSenderId: '806159169040',
    projectId: 'privora-9195c',
    storageBucket: 'privora-9195c.firebasestorage.app',
    iosBundleId: 'com.privora.privora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV8_VOXD47eRrdPlzzYz-nGaueJcH6lSs',
    appId: '1:806159169040:ios:b680c797a8ccab2f16fc95',
    messagingSenderId: '806159169040',
    projectId: 'privora-9195c',
    storageBucket: 'privora-9195c.firebasestorage.app',
    iosBundleId: 'com.privora.privora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDML2mI_9tuAHWTRQpkxO_jnZK-57OCpF4',
    appId: '1:806159169040:web:9fdb1ff7ede56d3716fc95',
    messagingSenderId: '806159169040',
    projectId: 'privora-9195c',
    authDomain: 'privora-9195c.firebaseapp.com',
    storageBucket: 'privora-9195c.firebasestorage.app',
    measurementId: 'G-D3H3NTJ4B7',
  );
}
